export const BREED_NAME_MAP = {
  "AFFENPINSCHER": "Affenpinscher",
  "AFGAN HOUND": "Afghan Hound",
  "AIDI": "Aidi",
  "AIREDALE TERRIER": "Airedale Terrier",
  "AKITA": "Akita",
  "AKITA AMERICANO": "American Akita",
  "ALANO ESPAÑOL (NO ACEPTADA FCI)": "Alano Español",
  "ALASKAN MALAMUTE": "Alaskan Malamute",
  "AMERICAN FOXHOUND": "American Foxhound",
  "AMERICAN HAIRLESS TERRIER (NO ACEPTADA FCI)": "American Hairless Terrier",
  "AMERICAN STAFFORDSHIRE TERRIER": "American Staffordshire Terrier",
  "ANTIGUO PERRO DE PASTOR INGLES": "Old English Sheepdog",
  "ARIEGEOIS": "Ariégeois",
  "AUSTRALIAN CATTLE DOG": "Australian Cattle Dog",
  "AUSTRALIAN STUMPY TAIL CATTLE DOG (PROV. ACEP.FCI)": "Australian Stumpy Tail Cattle Dog",
  "AUSTRALIAN TERRIER": "Australian Terrier",
  "AZAWAKH": "Azawakh",
  "BARBADO DA TERCEIRA (NO ACEPTADA FCI)": "Barbado da Terceira",
  "BARBET": "Barbet",
  "BASENJI": "Basenji",
  "BASSET ARTESIEN NORMAND": "Basset Artésien Normand",
  "BASSET AZUL DE GASCUÑA": "Blue Gascony Basset",
  "BASSET FAUVE DE BRETAGNE": "Basset Fauve de Bretagne",
  "BASSET HOUND": "Basset Hound",
  "BEAGLE": "Beagle",
  "BEAGLE-HARRIER": "Beagle-Harrier",
  "BEARDED COLLIE": "Bearded Collie",
  "BEDLINGTON TERRIER": "Bedlington Terrier",
  "BICHON BOLOÑES": "Bolognese dog",
  "BICHON FRISE": "Bichon Frisé",
  "BICHON HABANERO": "Havanese dog",
  "BICHON MALTES": "Maltese dog",
  "BIEWER TERRIER (NO ACEPTADA FCI)": "Biewer Terrier",
  "BILLY": "Billy dog",
  "BLACK AND TAN COONHOUND": "Black and Tan Coonhound",
  "BORDER COLLIE": "Border Collie",
  "BORDER TERRIER": "Border Terrier",
  "BORZOI": "Borzoi",
  "BOSTON TERRIER": "Boston Terrier",
  "BOUVIER BERNOIS": "Bernese Mountain Dog",
  "BOUVIER D'APPENZELL": "Appenzeller Sennenhund",
  "BOUVIER DE FLANDES": "Bouvier des Flandres",
  "BOUVIER DE L'ENTLEBUCH": "Entlebucher Mountain Dog",
  "BOUVIER DES ARDENNES": "Bouvier des Ardennes",
  "BOXER": "Boxer dog",
  "BRACO ALEMAN": "German Shorthaired Pointer",
  "BRACO DE AUVERNIA": "Auvergne Pointer",
  "BRACO DE WEIMAR": "Weimaraner",
  "BRACO DEL ARIEGE": "Ariege Pointer",
  "BRACO DEL BOURBONNAIS": "Bourbonnais Pointer",
  "BRACO ESLOVACO DE PELO DURO": "Slovak Rough-haired Pointer",
  "BRACO FRANCES - TIPO GASCUÑA": "French Pointing Dog Gascogne type",
  "BRACO FRANCES - TIPO PIRINEOS": "French Pointing Dog Pyrenean type",
  "BRACO HUNGARO DE PELO CORTO": "Vizsla",
  "BRACO HUNGARO DE PELO DURO": "Wirehaired Vizsla",
  "BRACO ITALIANO": "Bracco Italiano",
  "BRACO SAINT-GERMAIN": "Saint-Germain Pointer",
  "BRIQUET DE PROVENCE (NO ACEPTADA FCI)": "Briquet de Provence",
  "BRIQUET GRIFFON VENDEEN": "Briquet Griffon Vendéen",
  "BROHOLMER": "Broholmer",
  "BRUNO SAINT HUBERT FRANCAIS (NO ACEPTADA FCI)": "Bruno de Jura",
  "BULL TERRIER": "Bull Terrier",
  "BULL TERRIER MINIATURA": "Miniature Bull Terrier",
  "BULLDOG CONTINENTAL (PROV. ACEP. FCI.)": "Continental Bulldog",
  "BULLDOG FRANCES": "French Bulldog",
  "BULLDOG INGLES": "English Bulldog",
  "BULLMASTIFF": "Bullmastiff",
  "CAIRN TERRIER": "Cairn Terrier",
  "CAN DE CHIRA (GRUPO ETNICO)": "Can de Chira",
  "CAN DE PALLEIRO (NO ACEPTADA FCI)": "Can de Palleiro",
  "CANAAN DOG": "Canaan Dog",
  "CANE CORSO": "Cane Corso",
  "CANE DI MANNARA (NO ACEPTADA FCI)": "Cane di Mannara",
  "CANE DI OROPA (NO ACEPTADA FCI.)": "Cane di Oropa",
  "CANE FONNESE (NO ACEPTADA FCI)": "Cane Fonnese",
  "CANICHE": "Poodle",
  "CAO DA SERRA DA ESTRELA": "Estrela Mountain Dog",
  "CAO DA SERRA DE AIRES": "Portuguese Sheepdog",
  "CAO DE CASTRO LABOREIRO": "Castro Laboreiro Dog",
  "CAO DE FILA DE SAN MIGUEL": "Fila de São Miguel",
  "CAO DE GADO TRANSMONTANO (PROV. ACEP. FCI.)": "Transmontano Mastiff",
  "CAO DO BARROCAL ALGARVIO (NO ACEPTADA FCI)": "Barrocal Algarvian dog",
  "CAREA CASTELLANO-MANCHEGO (GRUPO ETNICO)": "Carea Castellano-Manchego",
  "CARLINO": "Pug",
  "CAVALIER KING CHARLES SPANIEL": "Cavalier King Charles Spaniel",
  "CESKY FOUSEK": "Český Fousek",
  "CESKY TERRIER": "Cesky Terrier",
  "CHESAPEAKE BAY RETRIEVER": "Chesapeake Bay Retriever",
  "CHIEN D'ARTOIS": "Chien d'Artois",
  "CHIEN DE SAINT-HUBERT": "Bloodhound",
  "CHIEN PLURICOLORE A POIL FRISE (NO ACEPTADA FCI)": "Chien Pluricolore à Poil Frisé",
  "CHIHUAHUA": "Chihuahua",
  "CHINESE CRESTED DOG": "Chinese Crested Dog",
  "CHONGQING DOG (NO ACEPTADA FCI)": "Chongqing dog",
  "CHOW CHOW": "Chow Chow",
  "CIMARRON URUGUAYO": "Cimarrón Uruguayo",
  "CIRNECO DELL'ETNA": "Cirneco dell'Etna",
  "CLUMBER SPANIEL": "Clumber Spaniel",
  "COCKER SPANIEL AMERICANO": "American Cocker Spaniel",
  "COCKER SPANIEL INGLES": "English Cocker Spaniel",
  "COTON DE TULEAR": "Coton de Tuléar",
  "CURLY-COATED RETRIEVER": "Curly-coated Retriever",
  "CURSINU (NO ACEPTADA FCI)": "Cursinu",
  "DACHSBRACKE DE LOS ALPES": "Alpine Dachsbracke",
  "DALMATA": "Dalmatian dog",
  "DANDIE DINMONT TERRIER": "Dandie Dinmont Terrier",
  "DEERHOUND": "Scottish Deerhound",
  "DEUTSCH DRAHTHAAR": "German Wirehaired Pointer",
  "DEUTSCH LANGHAAR": "Deutsch Langhaar",
  "DEUTSCHER STICHELHAAR": "German Roughhaired Pointer",
  "DOBERMANN": "Dobermann",
  "DOGO ALEMAN": "Great Dane",
  "DOGO ARGENTINO": "Dogo Argentino",
  "DOGO DE BURDEOS": "Dogue de Bordeaux",
  "DOGO DEL TIBET": "Tibetan Mastiff",
  "DOGO ESPAÑOL (GRUPO ETNICO)": "Spanish Mastiff",
  "DOGO MALLORQUIN": "Ca de Bou",
  "ENGLISH SPRINGER SPANIEL": "English Springer Spaniel",
  "EPAGNEUL BLEU DE PICARDIE": "Blue Picardy Spaniel",
  "EPAGNEUL BRETON": "Brittany Spaniel",
  "EPAGNEUL DE PONT-AUDEMER": "Pont-Audemer Spaniel",
  "EPAGNEUL DE SAINT-USUGE (NO ACEPTADA FCI)": "Saint-Usuge Spaniel",
  "EPAGNEUL FRANCES": "French Spaniel",
  "EPAGNEUL JAPONES": "Japanese Chin",
  "EPAGNEUL NAIN CONTINENTAL": "Papillon dog",
  "EPAGNEUL PICARD": "Picardy Spaniel",
  "EURASIER": "Eurasier",
  "FIELD SPANIEL": "Field Spaniel",
  "FILA BRASILEIRO": "Fila Brasileiro",
  "FLAT COATED RETRIEVER": "Flat-coated Retriever",
  "FOX TERRIER DE PELO DURO": "Wire Fox Terrier",
  "FOX TERRIER DE PELO LISO": "Smooth Fox Terrier",
  "FOXHOUND": "English Foxhound",
  "GALGO ESPAÑOL": "Spanish Greyhound",
  "GAMMEL DANSK HONSEHUND": "Old Danish Pointer",
  "GASCON SAINTONGEOIS": "Gascon Saintongeois",
  "GOLDEN RETRIEVER": "Golden Retriever",
  "GONCZY POLSKI": "Polish Hunting Dog",
  "GRAN BOUVIER SUIZO": "Greater Swiss Mountain Dog",
  "GRAN MÜNSTERLÄNDER": "Large Münsterländer",
  "GRAN SABUESO ANGLO-FRANCES BLANCO Y NARANJA": "Great Anglo-French White and Orange Hound",
  "GRAN SABUESO ANGLO-FRANCES BLANCO Y NEGRO": "Great Anglo-French White and Black Hound",
  "GRAN SABUESO ANGLO-FRANCES TRICOLOR": "Great Anglo-French Tricolour Hound",
  "GRAN SABUESO AZUL DE GASCUÑA": "Grand Bleu de Gascogne",
  "GRAND BASSET GRIFFON VENDEEN": "Grand Basset Griffon Vendéen",
  "GRAND GRIFFON VENDEEN": "Grand Griffon Vendéen",
  "GREYHOUND": "Greyhound",
  "GRIFFON BELGA": "Belgian Griffon",
  "GRIFFON D'ARRET A POIL DUR": "Wirehaired Pointing Griffon",
  "GRIFFON DE BRUSELAS": "Brussels Griffon",
  "GRIFFON FAUVE DE BRETAGNE": "Fawn Brittany Griffon",
  "GRIFFON NIVERNAIS": "Griffon Nivernais",
  "GRIFON AZUL DE GASCUÑA": "Grand Bleu de Gascogne",
  "GRONLANDS HUND": "Greenland Dog",
  "HARRIER": "Harrier dog",
  "HOKKAÏDO": "Hokkaido dog",
  "HOLLANDSE SMOUSHOND": "Hollandse Smoushond",
  "HOVAWART": "Hovawart",
  "IRISH GLEN OF IMAAL TERRIER": "Glen of Imaal Terrier",
  "IRISH SOFT COATED WHEATEN TERRIER": "Soft-coated Wheaten Terrier",
  "IRISH TERRIER": "Irish Terrier",
  "IRISH WOLFHOUND": "Irish Wolfhound",
  "JACK RUSSELL TERRIER": "Jack Russell Terrier",
  "JÄMTHUND": "Jämthund",
  "KAI": "Kai Ken",
  "KELPIE": "Australian Kelpie",
  "KERRY BLUE TERRIER": "Kerry Blue Terrier",
  "KING CHARLES SPANIEL": "King Charles Spaniel",
  "KISHU": "Kishu",
  "KLEINER MÜNSTERLÄNDER": "Small Münsterländer",
  "KOMONDOR": "Komondor",
  "KOREA JINDO DOG": "Korean Jindo Dog",
  "KROMFOHRLÄNDER": "Kromfohrländer",
  "KUVASZ": "Kuvasz",
  "LABRADOR RETRIEVER": "Labrador Retriever",
  "LAGOTTO ROMAGNOLO": "Lagotto Romagnolo",
  "LAÏKA DE SIBERIA OCCIDENTAL": "West Siberian Laika",
  "LAÏKA DE SIBERIA ORIENTAL": "East Siberian Laika",
  "LAIKA DE YAKUTIA (PROV. ACEP. FCI.)": "Yakutian Laika",
  "LAÏKA RUSO-EUROPEO": "Russo-European Laika",
  "LAKELAND TERRIER": "Lakeland Terrier",
  "LANCASHIRE HEELER (PROV. ACEP. FCI.)": "Lancashire Heeler",
  "LANDSEER": "Landseer dog",
  "LEBREL POLACO": "Chart Polski",
  "LEONBERGER": "Leonberger",
  "LHASA APSO": "Lhasa Apso",
  "LOBITO HERREÑO (GRUPO ETNICO)": "Lobito Herreño",
  "MAGYAR AGAR": "Magyar Agár",
  "MAJORERO (NO ACEPTADA FCI)": "Majorero",
  "MANCHESTER TERRIER": "Manchester Terrier",
  "MANETO (NO ACEPTADA FCI)": "Maneto",
  "MASTIFF": "Mastiff",
  "MASTIN DEL PIRINEO": "Pyrenean Mastiff",
  "MASTIN ESPAÑOL": "Spanish Mastiff",
  "MASTIN NAPOLITANO": "Neapolitan Mastiff",
  "MUDI": "Mudi",
  "NEDERLANDSE KOOIKERHONDJE": "Kooikerhondje",
  "NIHON SUPITTSU": "Japanese Spitz",
  "NORFOLK TERRIER": "Norfolk Terrier",
  "NORSK BUHUND": "Norwegian Buhund",
  "NORSK ELGHUND GRÄ": "Norwegian Elkhound",
  "NORSK ELGHUND SORT": "Black Norwegian Elkhound",
  "NORSK LUNDEHUND": "Norwegian Lundehund",
  "NORWICH TERRIER": "Norwich Terrier",
  "NOVA SCOTIA DUCK TOLLING RETRIEVER": "Nova Scotia Duck Tolling Retriever",
  "PACHON NAVARRO (NO ACEPTADA FCI)": "Pachón Navarro",
  "PARSON RUSSELL TERRIER": "Parson Russell Terrier",
  "PASTOR MINIATURA AMERICANO (PROV. ACEP. FCI.)": "Miniature American Shepherd",
  "PASTORE DELLA SILA (NO ACEPTADA FCI.)": "Pastore della Sila",
  "PEKINES": "Pekingese",
  "PEQUEÑO LEBREL ITALIANO": "Italian Greyhound",
  "PEQUEÑO PERRO RUSO (RUSSKIY TOY)": "Russian Toy",
  "PEQUEÑO SABUESO AZUL DE GASCUÑA": "Petit Bleu de Gascogne",
  "PERDIGUERO ALEMAN": "German Spaniel",
  "PERDIGUERO DE BURGOS": "Burgos Pointer",
  "PERDIGUERO DE DRENTE": "Drentsche Patrijshond",
  "PERDIGUERO PORTUGUES": "Portuguese Pointer",
  "PERRO DE AGUA AMERICANO": "American Water Spaniel",
  "PERRO DE AGUA ESPAÑOL": "Spanish Water Dog",
  "PERRO DE AGUA FRISON": "Wetterhoun",
  "PERRO DE AGUA IRLANDES": "Irish Water Spaniel",
  "PERRO DE AGUA PORTUGUES": "Portuguese Water Dog",
  "PERRO DE GRANJA DANES Y SUECO": "Danish-Swedish Farmdog",
  "PERRO DE MONTAÑA DE LOS PIRINEOS": "Great Pyrenees",
  "PERRO DE MUESTRA FRISON": "Stabyhoun",
  "PERRO DE NUTRIA": "Otterhound",
  "PERRO DE OSOS DE CARELIA": "Karelian Bear Dog",
  "PERRO DE PASTOR ALEMAN": "German Shepherd",
  "PERRO DE PASTOR AUSTRALIANO": "Australian Shepherd",
  "PERRO DE PASTOR BELGA": "Belgian Shepherd",
  "PERRO DE PASTOR BERGAMASCO": "Bergamasco Shepherd",
  "PERRO DE PASTOR BLANCO SUIZO": "Berger Blanc Suisse",
  "PERRO DE PASTOR CATALAN": "Catalan Sheepdog",
  "PERRO DE PASTOR DE ASIA CENTRAL": "Central Asian Shepherd Dog",
  "PERRO DE PASTOR DE BEAUCE": "Beauceron",
  "PERRO DE PASTOR DE BRIE": "Briard",
  "PERRO DE PASTOR DE KARST": "Karst Shepherd",
  "PERRO DE PASTOR DE PICARDIA": "Picardy Shepherd",
  "PERRO DE PASTOR DE RUSIA MERIDIONAL": "South Russian Ovcharka",
  "PERRO DE PASTOR DEL CAUCASO": "Caucasian Shepherd Dog",
  "PERRO DE PASTOR ESCOCES (ROUGH COLLIE)": "Rough Collie",
  "PERRO DE PASTOR GARAFIANO (NO ACEPTADA FCI)": "Garafian Shepherd",
  "PERRO DE PASTOR HOLANDES": "Dutch Shepherd",
  "PERRO DE PASTOR ISLANDES": "Icelandic Sheepdog",
  "PERRO DE PASTOR KANGAL": "Kangal Shepherd Dog",
  "PERRO DE PASTOR MALLORQUIN": "Ca de Bestiar",
  "PERRO DE PASTOR MAREMMANO-ABRUZZESE": "Maremma Sheepdog",
  "PERRO DE PASTOR POLACO DE LAS LLANURAS": "Polish Lowland Sheepdog",
  "PERRO DE PASTOR POLACO DE PODHALE": "Tatra Shepherd Dog",
  "PERRO DE PASTOR RUMANO DE BUCOVINA": "Bucovina Shepherd Dog",
  "PERRO DE PASTOR RUMANO DE LOS CARPATOS": "Carpathian Shepherd Dog",
  "PERRO DE PASTOR RUMANO DE MIORITZA": "Romanian Mioritic Shepherd Dog",
  "PERRO DE PASTOR VASCO (NO ACEPTADA FCI)": "Basque Shepherd Dog",
  "PERRO ESQUIMAL CANADIENSE": "Canadian Eskimo Dog",
  "PERRO FINLANDES DE LAPONIA": "Finnish Lapphund",
  "PERRO KINTAMANI-BALI (PROV. ACEP. FCI.)": "Kintamani",
  "PERRO LEONES DE PASTOR (NO ACEPTADA FCI)": "Leonese Shepherd Dog",
  "PERRO LOBO CHECOSLOVACO": "Czechoslovakian Wolfdog",
  "PERRO LOBO DE SAARLOOS": "Saarloos Wolfdog",
  "PERRO PASTOR BOHEMIO ( PROV. ACEP. FCI.)": "Bohemian Shepherd",
  "PERRO PASTOR BOSNIA-HERZEGOVINA Y CROACIA": "Bosnian and Herzegovinian Sheepdog",
  "PERRO PASTOR CROATO": "Croatian Sheepdog",
  "PERRO PASTOR DE LOS PIRINEOS DE CARA RASA": "Pyrenean Shepherd smooth-faced",
  "PERRO PASTOR DE LOS PIRINEOS DE PELO LARGO": "Pyrenean Shepherd long-haired",
  "PERRO PASTOR FINLANDES DE LAPONIA": "Lapponian Herder",
  "PERRO SIN PELO DEL PERU": "Peruvian Inca Orchid",
  "PERRO SUECO DE LAPONIA": "Swedish Lapphund",
  "PERRO TEJONERO DE WESTPHALIA": "Westphalian Dachsbracke",
  "PERRO TEJONERO SUECO": "Drever",
  "PETIT BASSET GRIFFON VENDEEN": "Petit Basset Griffon Vendéen",
  "PETIT BRABANÇON": "Petit Brabançon",
  "PETIT CHIEN LION": "Löwchen",
  "PINSCHER": "Pinscher",
  "PINSCHER AUSTRIACO": "Austrian Pinscher",
  "PODENCO ANDALUZ (NO ACEPTADA FCI)": "Andalusian Hound",
  "PODENCO CANARIO": "Canarian Warren Hound",
  "PODENCO DEL FARAON": "Pharaoh Hound",
  "PODENCO IBICENCO": "Ibizan Hound",
  "PODENCO ORITO ESPAÑOL (GRUPO ETNICO)": "Spanish Hound",
  "PODENCO PORTUGUES": "Portuguese Podengo",
  "PODENCO VALENCIANO (NO ACEPTADA FCI)": "Valencian Hound",
  "POINTER": "Pointer dog",
  "PORCELAINE": "Porcelaine dog",
  "PRESA CANARIO": "Presa Canario",
  "PRESA NAVARRO (BASATI ALAUNT) (GRUPO ETNICO)": "Presa Navarro",
  "PUDELPOINTER": "Pudelpointer",
  "PULI": "Puli dog",
  "PUMI": "Pumi dog",
  "RAFEIRO DO ALENTEJO": "Rafeiro do Alentejo",
  "RASTREADOR BRASILEÑO": "Brazilian Tracker",
  "RASTREADOR DE HANOVER": "Hanover Hound",
  "RASTREADOR MONTAÑES DE BAVIERA": "Bavarian Mountain Hound",
  "RATONERO DE PRAGA (PROV. ACEP. FCI)": "Prague Ratter",
  "RATONERO PALMERO (GRUPO ETNICO)": "Palmero Ratter",
  "RATONERO VALENCIANO (PROV. ACEP. FCI)": "Valencian Ratter",
  "RATONERO-BODEGUERO ANDALUZ (NO ACEPTADA FCI)": "Andalusian Rat Terrier",
  "RHODESIAN RIDGEBACK": "Rhodesian Ridgeback",
  "ROTTWEILER": "Rottweiler",
  "RUSSIAN TSVETNAYA BOLONKA (NO ACEPTADA FCI)": "Russian Tsvetnaya Bolonka",
  "SABUESO ALEMAN": "German Hound",
  "SABUESO ANGLO-FRANCES DE TAMAÑO MEDIANO": "Medium Anglo-French Hound",
  "SABUESO AUSTRIACO NEGRO Y FUEGO": "Austrian Black and Tan Hound",
  "SABUESO BOSNIO DE PELO CERDOSO - BARAK": "Bosnian Coarse-haired Hound",
  "SABUESO DE ESTONIA (PROV. ACEP. FCI.)": "Estonian Hound",
  "SABUESO DE HYGEN": "Hygenhund",
  "SABUESO DE ISTRIA DE PELO CORTO": "Istrian Shorthaired Hound",
  "SABUESO DE ISTRIA DE PELO DURO": "Istrian Coarse-haired Hound",
  "SABUESO DE MONTAÑA DEL MONTENEGRO": "Montenegrin Mountain Hound",
  "SABUESO DE SMALAND": "Smålandsstövare",
  "SABUESO DE TRANSILVANIA": "Transylvanian Hound",
  "SABUESO DEL TIROL": "Tyrolean Hound",
  "SABUESO DEL VALLE DE SAVE": "Posavac Hound",
  "SABUESO ESLOVACO": "Slovak Hound",
  "SABUESO ESPAÑOL": "Spanish Hound",
  "SABUESO ESTIRIO DE PELO DURO": "Styrian Coarse-haired Hound",
  "SABUESO FINLANDES": "Finnish Hound",
  "SABUESO FRANCES BLANCO Y NARANJA": "French White and Orange Hound",
  "SABUESO FRANCES BLANCO Y NEGRO": "French White and Black Hound",
  "SABUESO FRANCES TRICOLOR": "French Tricolour Hound",
  "SABUESO HALDEN": "Haldenstøver",
  "SABUESO HAMILTON": "Hamiltonstövare",
  "SABUESO HELENICO": "Hellenikos Ichnilatis",
  "SABUESO ITALIANO DE PELO CORTO": "Italian Short-haired Hound",
  "SABUESO ITALIANO DE PELO DURO": "Italian Wire-haired Hound",
  "SABUESO NORUEGO": "Norwegian Hound",
  "SABUESO POITEVIN": "Poitevin dog",
  "SABUESO POLACO": "Polish Hound",
  "SABUESO SCHILLER": "Schillerstövare",
  "SABUESO SERBIO": "Serbian Hound",
  "SABUESO SUIZO - CHIENS COURANTS SUISSES": "Swiss Hound",
  "SABUESO SUIZO PEQUEÑO": "Small Swiss Hound",
  "SABUESO TRICOLOR SERBIO": "Serbian Tricolour Hound",
  "SALUKI": "Saluki",
  "SAMOYEDO": "Samoyed dog",
  "SAN BERNARDO": "Saint Bernard dog",
  "SARPLANINAC": "Šarplaninac",
  "SCHAPENDOES": "Schapendoes",
  "SCHIPPERKE": "Schipperke",
  "SCHNAUZER GIGANTE": "Giant Schnauzer",
  "SCHNAUZER MEDIANO": "Standard Schnauzer",
  "SCHNAUZER MINIATURA": "Miniature Schnauzer",
  "SCOTTISH TERRIER": "Scottish Terrier",
  "SEALYHAM TERRIER": "Sealyham Terrier",
  "SEGUGIO DELL'APPENNINO (NO ACEPTADA FCI)": "Segugio dell'Appennino",
  "SEGUGIO MAREMMANO (PROV. ACEP. FCI.)": "Segugio Maremmano",
  "SETTER GORDON": "Gordon Setter",
  "SETTER INGLES": "English Setter",
  "SETTER IRLANDES ROJO": "Irish Red Setter",
  "SETTER IRLANDES ROJO Y BLANCO": "Irish Red and White Setter",
  "SHAR PEI": "Shar Pei",
  "SHETLAND SHEEPDOG": "Shetland Sheepdog",
  "SHIBA": "Shiba Inu",
  "SHIH TZU": "Shih Tzu",
  "SHIKOKU": "Shikoku dog",
  "SIBERIAN HUSKY": "Siberian Husky",
  "SILKY TERRIER": "Australian Silky Terrier",
  "SKYE TERRIER": "Skye Terrier",
  "SLOUGHI": "Sloughi",
  "SLOVENSKY CUVAC": "Slovak Cuvac",
  "SMOOTH COLLIE": "Smooth Collie",
  "SPINO DEGLI IBLEI (NO ACEPTADA FCI)": "Spino degli Iblei",
  "SPINONE ITALIANO": "Spinone Italiano",
  "SPITZ ALEMAN": "German Spitz",
  "SPITZ DE LOS VISIGODOS": "Swedish Vallhund",
  "SPITZ DE NORBOTTEN": "Norrbottenspets",
  "SPITZ FINLANDES": "Finnish Spitz",
  "STAFFORDSHIRE BULL TERRIER": "Staffordshire Bull Terrier",
  "SUSSEX SPANIEL": "Sussex Spaniel",
  "TAIWAN DOG": "Taiwan Dog",
  "TECKEL": "Dachshund",
  "TERRANOVA": "Newfoundland dog",
  "TERRIER ALEMAN DE CAZA": "German Hunting Terrier",
  "TERRIER BRASILEÑO": "Brazilian Terrier",
  "TERRIER JAPONES": "Japanese Terrier",
  "TERRIER NEGRO RUSO": "Black Russian Terrier",
  "THAI BANGKAEW DOG": "Thai Bangkaew Dog",
  "THAI RIDGEBACK DOG": "Thai Ridgeback",
  "TIBETAN SPANIEL": "Tibetan Spaniel",
  "TIBETAN TERRIER": "Tibetan Terrier",
  "TOSA": "Tosa Inu",
  "TOY FOX TERRIER (NO ACEPTADA FCI)": "Toy Fox Terrier",
  "TOY TERRIER": "English Toy Terrier",
  "VALDUEZA (NO ACEPTADA FCI)": "Valdueza Sheepdog",
  "VILLANO DE LAS ENCARTACIONES (NO ACEPTADA FCI)": "Villano de las Encartaciones",
  "VOLPINO ITALIANO": "Volpino Italiano",
  "WELSH CORGI CARDIGAN": "Cardigan Welsh Corgi",
  "WELSH CORGI PEMBROKE": "Pembroke Welsh Corgi",
  "WELSH SPRINGER SPANIEL": "Welsh Springer Spaniel",
  "WELSH TERRIER": "Welsh Terrier",
  "WEST HIGHLAND WHITE TERRIER": "West Highland White Terrier",
  "WHIPPET": "Whippet",
  "XOLOITZCUINTLE": "Xoloitzcuintle",
  "YORKSHIRE TERRIER": "Yorkshire Terrier",
  "ZWERGPINSCHER": "Miniature Pinscher",
};